In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [57]:
dataset=pd.read_csv("CKD.csv")
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [59]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [61]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv','wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 
                     'rbc_normal', 'pc_normal','pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes','appet_yes', 'pe_yes', 'ane_yes']]
dependent=dataset[['classification_yes']]

In [63]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [65]:
#standardisation
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [67]:
dataset['classification_yes'].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [69]:
from sklearn.svm import SVC

In [71]:
from sklearn.model_selection import GridSearchCV
param_grid={'kernel':['rbf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid= GridSearchCV(SVC(probability=True),param_grid,refit=True,verbose=3,cv=5,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


C:\Users\keert\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(cv=5, estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             scoring='f1_weighted', verbose=3)

In [73]:
re=grid.cv_results_
grid_predictions=grid.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [75]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print ("The f1-macro value for best parameter {}:". format(grid.best_params_),f1_macro)
print ("The confusion matrix:\n",cm)
print ("The report:\n",clf_report)

The f1-macro value for best parameter {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}: 0.9834018801410106
The confusion matrix:
 [[45  0]
 [ 2 73]]
The report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        45
           1       1.00      0.97      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.99      0.98       120
weighted avg       0.98      0.98      0.98       120



In [77]:
#roc-auc
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0        0.020169      0.005330         0.019828        0.001549       10   
1        0.026189      0.004556         0.018892        0.002395       10   
2        0.016689      0.004779         0.018385        0.002124       10   
3        0.011578      0.001643         0.014991        0.002060       10   
4        0.012649      0.003073         0.015012        0.004993       10   
5        0.021905      0.006444         0.015338        0.002273       10   
6        0.013603      0.004672         0.014333        0.002804       10   
7        0.013221      0.005246         0.016133        0.002973       10   
8        0.009905      0.002076         0.010859        0.001623      100   
9        0.016762      0.002830         0.016905        0.001661      100   
10       0.010408      0.001734         0.012456        0.001493      100   
11       0.008324      0.002407         0.009918        0.002369      100   
12       0.008746      0.002564         0.014970        0.000582      100   
13       0.016829      0.003151         0.012185        0.002547      100   
14       0.008607      0.002057         0.010940        0.002667      100   
15       0.009770      0.002083         0.013790        0.001342      100   
16       0.010674      0.002032         0.012388        0.002550     1000   
17       0.018750      0.003729         0.014279        0.000782     1000   
18       0.010814      0.001797         0.012090        0.003998     1000   
19       0.009760      0.002653         0.014834        0.002121     1000   
20       0.009707      0.000935         0.012876        0.001714     1000   
21       0.016397      0.001373         0.012926        0.003180     1000   
22       0.013100      0.003520         0.012032        0.002143     1000   
23       0.010004      0.001177         0.015808        0.001393     1000   
24       0.011878      0.001538         0.013828        0.001846     2000   
25       0.017477      0.000789         0.015188        0.000627     2000   
26       0.009867      0.002681         0.013893        0.002004     2000   
27       0.009015      0.002577         0.011122        0.001384     2000   
28       0.010680      0.001259         0.014355        0.002066     2000   
29       0.017157      0.001497         0.013744        0.001965     2000   
30       0.010881      0.002378         0.012551        0.002312     2000   
31       0.009476      0.001734         0.012277        0.002339     2000   
32       0.009230      0.000821         0.011723        0.002143     3000   
33       0.016509      0.001826         0.013119        0.002481     3000   
34       0.011123      0.002115         0.012111        0.001728     3000   
35       0.011337      0.001897         0.014296        0.000954     3000   
36       0.010384      0.001882         0.012306        0.002183     3000   
37       0.017208      0.001446         0.016450        0.000934     3000   
38       0.011298      0.003344         0.011940        0.001191     3000   
39       0.008578      0.002434         0.007618        0.003451     3000   

   param_gamma param_kernel  \
0         auto          rbf   
1         auto         poly   
2         auto      sigmoid   
3         auto       linear   
4        scale          rbf   
5        scale         poly   
6        scale      sigmoid   
7        scale       linear   
8         auto          rbf   
9         auto         poly   
10        auto      sigmoid   
11        auto       linear   
12       scale          rbf   
13       scale         poly   
14       scale      sigmoid   
15       scale       linear   
16        auto          rbf   
17        auto         poly   
18        auto      sigmoid   
19        auto       linear   
20       scale          rbf   
21       scale         poly   
22       scale      sigmoid   
23       scale       linear   
24        auto          rbf   
25        auto         poly   
26       

In [79]:
grid.predict([[15,60,3,0,86,15,0.6,138,4,11,33,7700,3.8,0,0,0,0,1,1,0,0,1,1,0,1,0,0]])

array([0])

In [81]:
h=roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])
print(h)

0.9997037037037036


In [83]:
grid.predict([[15,80,0,0,93,17,0.9,136,3.9,16.7,50,6200,5.2,1,0,0,0,1,1,0,0,0,0,0,1,0,0]])

array([0])